# Generated by Django 4.1.1 on 2023-04-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankaccount_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
