# Generated by Django 4.1.1 on 2023-04-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bankaccount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
