# Generated by Django 4.1.1 on 2023-04-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bankaccount_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='created',
        ),
    ]
