# Generated by Django 4.1.1 on 2023-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_bankaccount_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
