# Generated by Django 4.1.1 on 2023-04-05 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_bankaccount_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
