# Generated by Django 4.1.1 on 2023-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/img/profiles/user-default.png', null=True, upload_to='static/img/profiles/'),
        ),
    ]
