# Generated by Django 4.1.1 on 2023-04-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_bankaccount_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='currencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=10)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bankaccount')),
            ],
        ),
    ]
