# Generated by Django 4.1.1 on 2023-04-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currencytransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
