# Generated by Django 4.1.1 on 2023-04-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currencytransaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencytransaction',
            name='type',
        ),
    ]
