# Generated by Django 4.1.1 on 2023-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_remove_currencytransaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencytransaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
