# Generated by Django 4.1.1 on 2023-04-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_rename_user_id_currencytransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencytransaction',
            name='user',
        ),
    ]
