# Generated by Django 4.1.1 on 2023-04-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_remove_currencytransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
