# Generated by Django 4.1.1 on 2023-03-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankaccount_interest'),
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
